# Generated by Django 4.1.4 on 2022-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('ContactName', models.CharField(max_length=500)),
                ('ContactEmail', models.CharField(max_length=500)),
                ('ContactAddress', models.CharField(max_length=2000)),
                ('ContactPhone1', models.CharField(max_length=15)),
                ('ContactPhone2', models.CharField(max_length=15)),
                ('ContactType', models.CharField(max_length=100)),
            ],
        ),
    ]
